apiVersion: v1
kind: Service
metadata:
  name: adminer-deployment-service

spec: 
  type: NodePort
  ports: 
    - targetPort: 8080
      port: 8080
      nodePort: 30018
  selector: 
    app: sql-adminer
