apiVersion: apps/v1
kind: Deployment
metadata:
  name: gerrit-deployment
  labels:
    app: gerrit-meta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerrit
      type: frontend
  template:
    metadata:
      labels:
        app: gerrit
        type: frontend
    spec:
      containers:
      - name: gerrit
        image: gerritcodereview/gerrit
        env:
          - name: CANONICAL_WEB_URL
            value: https://ec2-3-21-39-210.us-east-2.compute.amazonaws.com:443
        volumeMounts:
        - mountPath: /var/gerrit/etc
          name: etc
        - mountPath: /var/gerrit/git
          name: git
        - mountPath: /var/gerrit/db
          name: db
        - mountPath: /var/gerrit/index
          name: index
        - mountPath: /var/gerrit/cache
          name: cache
        - mountPath: /var/gerrit/plugins
          name: plugins
        - mountPath: /var/gerrit/logs
          name: logs
        - mountPath: /var/gerrit/static
          name: static
        - mountPath: /var/gerrit/hooks
          name: hooks
        - mountPath: /var/gerrit/data
          name: data
        ports: 
         - containerPort: 8080
         - containerPort: 29418

      volumes:
      - name: etc
        hostPath:
            path: /data/gerrit323/etc
            type: Directory
      - name: git
        hostPath:
            path: /data/gerrit323/git
            type: Directory
      - name: db
        hostPath:
            path: /data/gerrit323/db
            type: Directory 
      - name: index
        hostPath:
            path: /data/gerrit323/index 
            type: Directory
      - name: cache
        hostPath:
            path: /data/gerrit323/cache
            type: Directory
      - name: plugins
        hostPath:
            path: /data/gerrit323/plugins 
            type: Directory
      - name: logs
        hostPath:
            path: /data/gerrit323/logs
            type: Directory
      - name: static
        hostPath:
            path: /data/gerrit323/static
            type: Directory
      - name: hooks
        hostPath:
            path: /data/gerrit323/hooks
            type: Directory
      - name: data
        hostPath:
            path: /data/gerrit323/data
            type: Directory
