apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-number
  labels: 
    app: random-number
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-number1
  template:
    metadata:
      labels:
        app: random-number1
    spec: 
      containers:
      - name: alpine
        image: alpine
        command: ["/bin/sh", "-c",]
        args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
