apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vol
  labels: 
    app: nginx-vol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-vol1
  template:
    metadata:
      labels:
        app: nginx-vol1
    spec: 
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name:  data-volume
            mountPath: /usr/share/nginx/html/
      volumes:
      - name:  data-volume
        hostPath:
          path: /data/html/
          type: Directory
