apiVersion: v1
kind: Service
metadata:
  name: drupal-service

spec: 
  type: NodePort
  ports: 
    - port: 80
      targetPort: 0
      nodePort: 30010
  selector: 
      app: drupal
      type: frontend
